version: '3.8'

services:
  db:
    image: eduardomokfa/equoterapia_database:0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_DATABASE: equoterapia
    ports:
      - "3306:3306"
    volumes:
      - ./dados-mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - |
          mysql -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} \
          --database $${MYSQL_DATABASE} -e 'SHOW TABLES' | \
          [ $$(wc -l) -gt 10 ]
      interval: 10s 
      timeout: 5s 
      retries: 3
    networks: ['mynetwork']
    
  backend:
    build:
      context: /backend/.
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks: ['mynetwork']  

  frontend:
    build:
      context: /frontend/.
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    networks: ['mynetwork']  


networks: {mynetwork: {}}